const main = 'http://android.dealtichtac.com/android/';
export default url = {
  LOGIN           : `${main}login.php`,
  DANHSACHLOGIN   : `${main}danhsachuser.php`,
  LINK_WEB        : `${main}addproduct_json.php`,
  MAIN_KIEMKHO_URL: `${main}danhsach_kiemkho.php`,
  MAIN_BH_BH1DOI1 : `${main}danhsach_bh1d1.php`,
  MAIN_BH_BHHT    : `${main}danhsach_bhht.php`,
  MAIN_BH_BHDLK   : `${main}danhsach_bhdlk.php`,
  MAIN_MENU_DSCH  : `${main}danhsach_chinhanh.php`,
  DANHSACHDICA    : `${main}danhsach_dica.php`,
  MAIN_QUATANG    : `${main}danhsach_quatang.php`,
  MAIN_CHITIEU_NV : `${main}danhsach_chitieunhanvien.php`,
  MAIN_KHUYENMAI  : `${main}danhsach_khuyenmai.php`,
  MAIN_CHUONGTRINH: `${main}danhsach_chuongtrinh.php`,
  UPLOAD_AVATAR   : `${main}upload_avatar.php`,
  LINK_AVATAR     : `${main}avatar/`,
  MAIN_VERSION    : `${main}danhsach_version.php`,
  MAIN_LINKAVATAR : `${main}linkavatar.php`,
  MAIN_TIENTRAVE  : `${main}danhsach_tientrave.php`,
  MAIN_PHICOD     : `${main}danhsach_phicod.php`,
  MAIN_BH_BHCXL   : `${main}danhsach_bhcxl.php`,
  MAIN_BH_BHDDT   : `${main}danhsach_bhddt.php`,
  LINK_WEB_XUATNHA: `${main}addXuatnhap.php`,
  LINK_WEB_V2     : `${main}addV2.php`,
  MAIN_XUATNHAP   : `${main}danhsach_xuatnhap.php`,
  MAIN_KHOANCHI   : `${main}danhsach_khoanchi.php`,
  MAIN_DATCOC     : `${main}danhsach_datcoc.php`,
  MAIN_DOANHTHU   : `${main}danhsach_doanhthu.php`,
  MAIN_REALTIME   : `${main}danhsach_realtime_order.php`,
  MAIN_MAGIAMGIA  : `${main}danhsach_magiamgia.php`,
  MAIN_LISTSOLUONG: `${main}danhsach_listsoluong.php`,
  CHECKKHACHHANG  : `${main}danhsach_checkkhachhang.php`,
  MAIN_DANHMUC    : `${main}danhsach_danhmuc.php`,
  MAIN_DANHMUC_V2 : `${main}danhsach_danhmucv2.php`,
  MAIN_MASTER     : `${main}danhsach_master.php`,
  MAIN_KHO        : `${main}danhsach_kho.php`,
  MAIN_MINSTOCK   : `${main}danhsach_minstock.php`,
}